### ISSUE TITLE
Thoughts about yaml for tests

### ISSUE THREAD

**Issue by mhebing** [ddionrails/testsuite#15]
```yaml
compare_keys:
  x:
    dataset: ap
    variable: id
  y:
    dataset: ah
    variable: f_key
```

```python
for key, values in yaml_dict.items():
    function = eval(key)  # function() == compare_keys()
    function(**values)    # compare_keys(x = dict(dataset="ap", variable="id"), y=…)
```
